### ISSUE TITLE
Accessing CSnap from /demos/<PK> doesn't hide the title bar

### ISSUE THREAD

**Issue by chuck211991** [CSnap/rpi_csdt_community#24]
And it is not possible to get rid of it. This is an issue when someone "shares" the demo URL.

**Comment by chuck211991** [comment]
Does not currently do this.

**Comment by BenjaminDHorne** [comment]
Charles, just so you know. I think the Github issue tracker has not been
used in a while. So this stuff is probably all old. (Although I agree that
it should be used).
