### ISSUE TITLE
HIGH PRIORITY: Clicking File button in CSnap brings up Open from hard disk instead of internal CSnap file menu

### ISSUE THREAD

**Issue by ibara** [CSnap/rpi_csdt_community#33]
I recorded a video of this. Cannot reproduce locally.

**Comment by chuck211991** [comment]
Could you provide a link to the video? Drop is on blackrain if you need someplace to put it

**Comment by ibara** [comment]
Did you set me up on blackrain?

**Comment by chuck211991** [comment]
Yeah, so that you would someplace to upload videos and data from the Cleveland trip... You need to be on campus, but you should be able to login as bcallahan using your SSH key

**Comment by ibara** [comment]
Blah! Of course I read this as soon as I get home.
OK. I'll send it your way next time I'm up on campus. Or just show you. Whichever comes first.

**Comment by ibara** [comment]
Laquana hit it again in her class tonight. It happened when a student clicked File->Import then clicked cancel and then pressed the File button. No idea why we didn't hit it this morning.

Also, we're still hitting the file save bug. Any way you can push just that to the community site?

**Comment by chuck211991** [comment]
I can't reproduce and still haven't seen the video... I'm going to mark this as low priority and ignore it for now :-P

**Comment by ibara** [comment]
I haven't seen it lately either, so happy to keep this low for now.
