### ISSUE TITLE
Classroom Projects Do Not Show Up

### ISSUE THREAD

**Issue by SillyInventor** [CSnap/rpi_csdt_community#49]
from John

**Comment by chuck211991** [comment]
Just a reminder that members and projects won't show up until the classroom leader approves them...

**Comment by JamesHoustonDavis** [comment]
He did approve them.... However, I can't seem to replicate the problem on my computer. It's possibly an old problem, and we can just delete and recreate the classroom.

**Comment by hughed2** [comment]
Has Django been updated? A lot of what I did for classrooms was done specifically for the version of Django we were using as of a month ago and needs to be updated when Django is. I sent out some instructions and pointers on what needs to be changed and how.

If it's not Django, could you be a bit more specific? If it's on the community or dev site, what classroom, what users, what project? If it's not on the community or dev site, can you recreate it there so I can access it?

**Comment by BenjaminDHorne** [comment]
Django has not been updated to my knowledge.

**Comment by chuck211991** [comment]
I can currently see projects when looking at a classroom; please reopen if the issue reappears.
