### ISSUE TITLE
Classroom Application Filter Request

### ISSUE THREAD

**Issue by SillyInventor** [CSnap/rpi_csdt_community#52]
need application filter so that teachers can view student projects sorted by lesson

From John

**Comment by chuck211991** [comment]
This was completed some time ago.

**Comment by SillyInventor** [comment]
... was it? I don't see it.

**Comment by SillyInventor** [comment]
Also, it's none of my business... but the classroom admin seems to be broken.

**Comment by chuck211991** [comment]
Ah, perhaps I was too hasty. Is this for teachers viewing projects sorted by lessons (where lesson would be application type?), or something else?

We are currently using django_teams, not the "classrooms" as written in the community site code itself. I'll go ahead and remove the classroom objects from the codebase.

**Comment by SillyInventor** [comment]
That's exactly what it is for.

I meant, when I  went to check the presence of the feature the... team teacher / administration view didn't work...


Sent from my T-Mobile 4G LTE Device


-------- Original message --------
